FROM alpine:3.16

ARG ZIP_PKG

RUN apk add --no-cache \
  openjdk11 \
  unzip

ENV JAVA_HOME /usr/lib/jvm/java-11-openjdk
ENV PATH $PATH:$JAVA_HOME/bin
ENV DB_AGENT_HOME /opt/appdynamics

COPY $ZIP_PKG /tmp/$ZIP_PKG

RUN mkdir -p $DB_AGENT_HOME \
  && unzip -oq /tmp/$ZIP_PKG -d $DB_AGENT_HOME \
  && rm /tmp/$ZIP_PKG

WORKDIR $DB_AGENT_HOME

COPY startup.sh .
RUN chmod +x startup.sh

CMD "./startup.sh"
